In [7]:
import numpy as np

In [37]:
def convert2_bin(state_number, N):
    binary = bin(state_number)[2:]
    return "0"*(N-len(binary))+binary



In [69]:
convert2_bin(2,3)


'010'

In [91]:
def ising_operator(state_vector, J=12, g=100):
    N = int(np.log2(len(state_vector)))
    resulting_vector = np.zeros(state_vector.shape)
    for state_number in range(len(state_vector)):
        if state_vector[state_number] == 0:
            continue
        
        binary = convert2_bin(state_number, N)
        a = 0
        
        for i in range(len(binary)-1):
            a += 1 if binary[i]==binary[i+1] else -1
        resulting_vector[int(binary, 2)] = J*a
        
        for i in range(len(binary)):
            new_binary = binary[:i] + str(int(binary[i]=="0")) + binary[i+1:]
            resulting_vector[int(new_binary, 2)] = -g
    return resulting_vector
    

In [68]:
ising_operator(np.array([0,0,1,0,0,0,0,0]))

array([-100.,    0.,  -24., -100.,    0.,    0., -100.,    0.])

In [93]:
def hamiltonian_matrix(N):
    v_ising_operator = np.vectorize(ising_operator,signature='(n)->(n)')
    return v_ising_operator(np.eye(2**N))
print(hamiltonian_matrix(3))

[[  24. -100. -100.    0. -100.    0.    0.    0.]
 [-100.    0.    0. -100.    0. -100.    0.    0.]
 [-100.    0.  -24. -100.    0.    0. -100.    0.]
 [   0. -100. -100.    0.    0.    0.    0. -100.]
 [-100.    0.    0.    0.    0. -100. -100.    0.]
 [   0. -100.    0.    0. -100.  -24.    0. -100.]
 [   0.    0. -100.    0. -100.    0.    0. -100.]
 [   0.    0.    0. -100.    0. -100. -100.   24.]]


In [94]:
def hamiltonian_elements(N,state):
    Hs = ising_operator(np.eye(2**N)[state])
    result = []
    for i in range(len(Hs)):
        if Hs[i] == 0:
            continue
        result.append((Hs[i],i))
    return result
    

In [95]:
hamiltonian_elements(3,0)

[(24.0, 0), (-100.0, 1), (-100.0, 2), (-100.0, 4)]

In [ ]:
N = 4
J = 1/4
g = 1/2
    